TEST_AVIA_SERVICE_DETAILS_RESPONSE = {
    'product': {
        'flight': {
            'id': 'id',
            'rid': 'rid',
            'tariff_type': None,
            'fare_family_type': 'SMARTLIGHT',
            'fare_family_flag': True,
            'segments_count': 2,
            'type': 'regular',
            'is_inner_flight': True,
            'is_baggage': True,
            'is_refund': False,
            'is_subsidized': False,
            'citizenships': None,
            'is_vtrip': False,
            'office_id': '8308',
            'provider': {
                'gds': 4,
                'name': 'TUA',
                'supplier': {
                    'id': 1080,
                    'code': '5N',
                    'title': 'Смартавиа',
                },
            },
            'price': {
                'RUB': {
                    'fare': 240,
                    'fee': 0,
                    'taxes': 200,
                    'amount': 440,
                },
            },
            'extra_baggage': [],
            'segments': [
                {
                    'arrival': {
                        'date': '27.08.2022',
                        'time': '13:40',
                        'datetime': '27.08.2022 13:40:00',
                        'timezone': 'Europe/Moscow',
                        'timezone_offset': '3',
                        'timestamp': 1661596800,
                        'terminal': '1',
                        'airport': {
                            'id': 80431,
                            'title': 'Пулково',
                            'short_title': '',
                            'code': 'LED',
                        },
                        'city': {
                            'id': 7069620,
                            'code': 'LED',
                            'title': 'Санкт-Петербург',
                        },
                        'region': {
                            'id': None,
                            'code': None,
                            'title': None,
                        },
                        'country': {
                            'id': 191,
                            'code': 'RU',
                            'title': 'Россия',
                        },
                    },
                    'departure': {
                        'date': '27.08.2022',
                        'time': '12:00',
                        'datetime': '27.08.2022 12:00:00',
                        'timezone': 'Europe/Moscow',
                        'timezone_offset': '3',
                        'timestamp': 1661590800,
                        'terminal': '',
                        'airport': {
                            'id': 80750,
                            'title': 'Домодедово',
                            'short_title': '',
                            'code': 'DME',
                        },
                        'city': {
                            'id': 64192,
                            'code': 'MOW',
                            'title': 'Москва',
                        },
                        'region': {
                            'id': None,
                            'code': None,
                            'title': None,
                        },
                        'country': {
                            'id': 191,
                            'code': 'RU',
                            'title': 'Россия',
                        },
                    },
                    'seats': 9,
                    'flight_number': '295',
                    'direction': 0,
                    'duration': {
                        'flight': {
                            'common': 100,
                            'hour': 1,
                            'minute': 40,
                        },
                    },
                    'route_duration': 100,
                    'is_baggage': True,
                    'baggage': {
                        'piece': 0,
                        'weight': None,
                    },
                    'comment': 'comment',
                    'cbaggage': {
                        'piece': 1,
                        'weight': 10,
                        'dimensions': '30x40x50cm',
                    },
                    'is_refund': False,
                    'is_change': True,
                    'class': {
                        'type_id': 1,
                        'name': 'E',
                        'service': 'R',
                    },
                    'is_first': True,
                    'is_last': True,
                    'fare_code': 'RLTOW',
                    'carrier': {
                        'id': 1080,
                        'title': 'Smartavia',
                        'code': '5N',
                    },
                    'aircraft': {
                        'code': '738',
                        'title': 'Boeing 737-800',
                    },
                    'stops': [],
                    'provider': {
                        'gds': 4,
                        'name': 'TUA',
                        'supplier': {
                            'id': 1080,
                            'title': 'Smartavia',
                            'code': '5N',
                        },
                    },
                    'type': 'regular',
                    'trip_id': '',
                    'locator': '',
                },
                {
                    'arrival': {
                        'date': '01.09.2022',
                        'time': '16:20',
                        'datetime': '01.09.2022 16:20:00',
                        'timezone': 'Europe/Moscow',
                        'timezone_offset': '3',
                        'timestamp': 1662038400,
                        'terminal': '',
                        'airport': {
                            'id': 80750,
                            'title': 'Домодедово',
                            'short_title': '',
                            'code': 'DME',
                        },
                        'city': {
                            'id': 64192,
                            'code': 'MOW',
                            'title': 'Москва',
                        },
                        'region': {
                            'id': None,
                            'code': None,
                            'title': None,
                        },
                        'country': {
                            'id': 191,
                            'code': 'RU',
                            'title': 'Россия',
                        },
                    },
                    'departure': {
                        'date': '01.09.2022',
                        'time': '14:40',
                        'datetime': '01.09.2022 14:40:00',
                        'timezone': 'Europe/Moscow',
                        'timezone_offset': '3',
                        'timestamp': 1662032400,
                        'terminal': '1',
                        'airport': {
                            'id': 80431,
                            'title': 'Пулково',
                            'short_title': '',
                            'code': 'LED',
                        },
                        'city': {
                            'id': 7069620,
                            'code': 'LED',
                            'title': 'Санкт-Петербург',
                        },
                        'region': {
                            'id': None,
                            'code': None,
                            'title': None,
                        },
                        'country': {
                            'id': 191,
                            'code': 'RU',
                            'title': 'Россия',
                        },
                    },
                    'seats': 9,
                    'flight_number': '296',
                    'direction': 1,
                    'duration': {
                        'flight': {
                            'common': 100,
                            'hour': 1,
                            'minute': 40,
                        },
                    },
                    'route_duration': 100,
                    'is_baggage': True,
                    'baggage': {
                        'piece': 0,
                        'weight': None,
                    },
                    'comment': 'comment',
                    'cbaggage': {
                        'piece': 1,
                        'weight': 10,
                        'dimensions': '20x30x30cm',
                    },
                    'is_refund': False,
                    'is_change': True,
                    'class': {
                        'type_id': 1,
                        'name': 'E',
                        'service': 'R',
                    },
                    'is_first': True,
                    'is_last': True,
                    'fare_code': 'RLTOW',
                    'carrier': {
                        'id': 1080,
                        'title': 'Smartavia',
                        'code': '5N',
                    },
                    'aircraft': {
                        'code': '738',
                        'title': 'Boeing 737-800',
                    },
                    'stops': [],
                    'provider': {
                        'gds': 4,
                        'name': 'TUA',
                        'supplier': {
                            'id': 1080,
                            'title': 'Smartavia',
                            'code': '5N',
                        },
                    },
                    'type': 'regular',
                    'trip_id': '',
                    'locator': '',
                },
            ],
            'segments_direction': [
                [
                    0,
                ],
                [
                    1,
                ],
            ],
            'pricer_info': None,
            'discount_rule': None,
            'booking_with_partial_data_allowed': False,
            'booking_actualization_from_gds_allowed': False,
            'discount': None,
            'online_registration': {
                'price': 600,
                'is_available': True,
            },
        },
        'tickets': [
            {
                'can_be_refunded': False,
                'allow_set_fare_families': False,
                'is_refund': False,
                'is_refunded': False,
                'status': 'Booked',
                'locator': '',
                'display_locator': '',
                'vnd_locators': '',
                'booking_provider': 'TUA',
                'provider': {
                    'gds': None,
                    'name': 'TUA',
                    'currency': 'RUB',
                },
                'duration': {
                    'common': 200,
                    'hour': 3,
                    'minute': 0,
                },
                'locations': [
                    {
                        'departure': {
                            'date': '27.08.2022',
                            'time': '12:00',
                            'datetime': '27.08.2022 12:00:00',
                            'timezone': 'Europe/Moscow',
                            'timezone_offset': '3',
                            'timestamp': 1661590800,
                            'terminal': '',
                            'airport': {
                                'id': 80750,
                                'title': 'Домодедово',
                                'short_title': '',
                                'code': 'DME',
                            },
                            'city': {
                                'id': 64192,
                                'code': 'MOW',
                                'title': 'Москва',
                            },
                            'region': {
                                'id': None,
                                'code': None,
                                'title': None,
                            },
                            'country': {
                                'id': 191,
                                'code': 'RU',
                                'title': 'Россия',
                            },
                        },
                        'arrival': {
                            'date': '27.08.2022',
                            'time': '13:40',
                            'datetime': '27.08.2022 13:40:00',
                            'timezone': 'Europe/Moscow',
                            'timezone_offset': '3',
                            'timestamp': 1661596800,
                            'terminal': '1',
                            'airport': {
                                'id': 80431,
                                'title': 'Пулково',
                                'short_title': '',
                                'code': 'LED',
                            },
                            'city': {
                                'id': 7069620,
                                'code': 'LED',
                                'title': 'Санкт-Петербург',
                            },
                            'region': {
                                'id': None,
                                'code': None,
                                'title': None,
                            },
                            'country': {
                                'id': 191,
                                'code': 'RU',
                                'title': 'Россия',
                            },
                        },
                        'direction': 0,
                    },
                    {
                        'departure': {
                            'date': '01.09.2022',
                            'time': '14:40',
                            'datetime': '01.09.2022 14:40:00',
                            'timezone': 'Europe/Moscow',
                            'timezone_offset': '3',
                            'timestamp': 1662032400,
                            'terminal': '1',
                            'airport': {
                                'id': 80431,
                                'title': 'Пулково',
                                'short_title': '',
                                'code': 'LED',
                            },
                            'city': {
                                'id': 7069620,
                                'code': 'LED',
                                'title': 'Санкт-Петербург',
                            },
                            'region': {
                                'id': None,
                                'code': None,
                                'title': None,
                            },
                            'country': {
                                'id': 191,
                                'code': 'RU',
                                'title': 'Россия',
                            },
                        },
                        'arrival': {
                            'date': '01.09.2022',
                            'time': '16:20',
                            'datetime': '01.09.2022 16:20:00',
                            'timezone': 'Europe/Moscow',
                            'timezone_offset': '3',
                            'timestamp': 1662038400,
                            'terminal': '',
                            'airport': {
                                'id': 80750,
                                'title': 'Домодедово',
                                'short_title': '',
                                'code': 'DME',
                            },
                            'city': {
                                'id': 64192,
                                'code': 'MOW',
                                'title': 'Москва',
                            },
                            'region': {
                                'id': None,
                                'code': None,
                                'title': None,
                            },
                            'country': {
                                'id': 191,
                                'code': 'RU',
                                'title': 'Россия',
                            },
                        },
                        'direction': 1,
                    },
                ],
            },
        ],
        'passengers': [
            {
                'id': 1,
                'person_id': None,
                'rph': '1.1',
                'age': 32,
                'birthday': '07.07.1990',
                'citizenship': 'RU',
                'document': {
                    'type': 'C',
                    'num': '1234123423',
                    'expire': '',
                },
                'email': 'ivanov1224242342342424@mail.ru',
                'gender': 'M',
                'phone': '+791091091234',
                'bonus_card': None,
                'bonus_card_supplier': None,
                'name': {
                    'last': 'IVANOV',
                    'first': 'IVAN',
                    'middle': None,
                    'first_en': None,
                    'last_en': None,
                    'middle_en': None,
                    'first_ru': None,
                    'last_ru': None,
                    'middle_ru': None,
                },
                'company': None,
                'attributes': [],
                'send_email': None,
                'preferences': None,
                'travel_policy_id': 295,
                'is_refunded': False,
                'is_anNoneed': False,
                'type': 'adt',
                'is_private_person': False,
                'passenger_tickets': [
                    {
                        'ticket_number': '',
                        'is_refunded': False,
                        'is_anNoneed': False,
                        'ticket_status': 'Booked',
                    },
                ],
                'available_documents': {
                    'ru': [
                        'C',
                        'P',
                        'M',
                        'S',
                    ],
                    'other': [
                        'A',
                    ],
                },
            },
        ],
        'is_travel_policy_compliant': True,
    },
}
